#!/usr/bin/env bash
#Install nginx web server
apt-get  -y update && apt-get -y upgrade
apt-get -y install nginx
ufw allow 'Nginx HTTp'
echo 'Hello World\!' > /var/www/html/index.nginx-debianhtml
service nginx restart
