#!/usr/bin/env bash  
#Configure your Nginx server so that /redirect_me is redirecting to another page   
apt  -y update && apt -y upgrade
apt -y install nginx
ufw allow 'Nginx'
echo 'Hello World\!' > /var/www/html/index.html
new-page="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/listen 80 default_server/a $(new-page)" /etc/nginx/sites-available/default
service nginx restart
