#!/usr/bin/env bash  
#Configure your Nginx server so that /redirect_me is redirecting to another page   
apt  -y update
apt -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i 's/location \/ {/location \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com;\n}\n\nlocation \/ {\n\troot \/var\/www\/html;\n\tindex index.html;\n}/g' /etc/nginx/sites-available/default
service nginx restart
