#!/usr/bin/env bash  
#Configure your Nginx server so that /redirect_me is redirecting to another page   
apt  -y update
apt -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^ \/redirect_me return 301 https:\/\/www.youtube.com permanent;' /etc/nginx/sites-available/default
service nginx restart
