#!/usr/bin/env bash 
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.  
apt  -y update 
apt -y upgrade
apt -y install nginx
ufw allow 'Nginx'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html 
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default 
service nginx restart
