#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt -y update
sudo apt -y install nginx
host = $(hostname)
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $host;' /etc/nginx/sites-available/default
sudo service nginx restart
