#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo sed -i  '/http {/a \    server {\n        listen 80 default_server;\n      listen [::]:80 default_server;\n    }' /etc/nginx/nginx.conf
sudo service nginx restart
