#!/usr/bin/env bash
# This script prints "To infinity and beyond indefinitely" indefinitely, with a sleep 2 in between each iteration.
# It also prints "I am invincible!!!" when receiving a SIGTERM signal.
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
  echo "To infinity and beyond"
  sleep 2
done
