#!/usr/bin/env bash
# This script is displaying The content of the current directory
#  In a list format
#  Where only the part of the name after the first dash is displayed
for file in *
do
  # Check if file is hidden
  if [[ $file == .* ]]; then
    continue
  fi
  
  # Get the part of the name after the first dash
  name=$(echo "$file" | cut -d'-' -f2-)

  # Print the modified name
  echo "$name"
done
